title: My Blog
theme: minima
author: Luis Alejandro Cuasquer Cruz
email: lacuasquer@misena.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Este es mi sitio con jekyll, en el cual publicaré algunos articulos.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
